### PR TITLE
(S) As a visitor on the landing page I want to sign up for Sacred Art's mailing list to stay informed

### PR DESCRIPTION
**Pull request by bethios**

### CODE REVIEW

**Comment by bethios** [comment]
https://sacred-art-development.herokuapp.com/

https://trello.com/c/rJAIf0xD/29-s-as-a-visitor-on-the-landing-page-i-want-to-sign-up-for-sacred-art-s-mailing-list-see-store-hours-and-address-to-stay-informed

**Comment by bethios** [comment]
[(S) As a visitor on the landing page I want to sign up for Sacred Art's mailing list, see store hours and address to stay informed](https://trello.com/c/rJAIf0xD/29-s-as-a-visitor-on-the-landing-page-i-want-to-sign-up-for-sacred-art-s-mailing-list-see-store-hours-and-address-to-stay-informed)

**Comment by cblant20** [comment]
typing in the newsletter form doesn't work (text is white).

only exists on footer and not contact page

**Comment by cblant20** [comment]
this seems to be the other code and not this code.

shouldn't the newsletter form be a partial?

**Pull request merged**
